### ISSUE TITLE
Invalid commit for `xpcc` submodule

### ISSUE THREAD

**Issue by ekiwi** [salkinium/upainter#2]
I cannot checkout the commit that you specified for the xpcc submodule:

```
> git submodule update 
fatal: reference is not a tree: 79d292b7684563182eebad14ccab1ec88cfbed73
Unable to checkout '79d292b7684563182eebad14ccab1ec88cfbed73' in submodule path 'xpcc'
```

**Comment by salkinium** [comment]
Sorry, didn't push my local changes.
You might need to do `git submodule sync` after pulling the changes (?).

**Comment by salkinium** [comment]
I plan to cherry-pick some of the commits on the `project/upainter` branch to a new branch and make a PR out of it, but I first wanted to get it working.
